version: '3'

services:
  db:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hierarch_test
    ports:
      - 5432:5432
